name: 01 Hello World

on:
  workflow_call:
  
  jobs:
    01-hello-world:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2
        
        - name: Print Hello World
          run: |
            echo "Hello World"
